package ex3;

import java.util.Locale;

/*Exercise 3: (4) Write a method that creates and initializes a twodimensional array of
double. The size of the array is determined by the arguments of the method, and the
initialization values are a range determined by beginning and ending values that are also
arguments of the method. Create a second method that will print the array generated by the
first method. In main( ) test the methods by creating and printing several different sizes of
arrays.*/

public class MyClass {

	private static double[][] method1(int a, int b, double start, double end) {
		double[][] result = new double[a][b];
		double incr = (end - start) / (a * b);
		double val = start;
		for (int i = 0; i < a; i++) {
			for (int j = 0; j < b; j++) {
				result[i][j] = val;
				val += incr;
			}
		}
		return result;
	}

	private static void method2(double[][] da) {
		for (int i = 0; i < da.length; i++) {
			double[] temp = da[i];
			for (int j = 0; j < temp.length; j++) {
				System.out.printf(Locale.US, "%.2f", da[i][j]);
				System.out.print(" ");
			}
			System.out.println();
		}
	}

	public static void main(String[] args) {
		method2(method1(3, 2, 22.0, 23.9));

	}

}
